language: go
go_import_path: github.com/mrlsd/echo-cms
go:
  - 1.6
  - 1.7
  - tip
before_install:
  - go get github.com/labstack/echo
  - go get github.com/gavv/httpexpect
  - go get github.com/spf13/viper
script:
  - go build server.go
matrix:
  allow_failures:
    - go: tip
